services:
  - type: web
    name: maxitsa
    env: php
    buildCommand: composer install --no-dev
    startCommand: php -S 0.0.0.0:$PORT -t public/
    envVars:
      - key: DB_DSN
        value: "pgsql:host=aws-0-eu-west-3.pooler.supabase.com;port=5432;dbname=postgres"
      - key: DB_DRIVER
        value: pgsql  
      - key: DB_HOST
        value: aws-0-eu-west-3.pooler.supabase.com
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        fromDatabase:
          name: maxitsa-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: maxitsa-db
          property: laye1234